name: flutter_app
description: A Flutter mobile application
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # مكتبات نظام الترخيص والحماية
  flutter_secure_storage: ^9.2.2
  ntp: ^2.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  crypto: ^3.0.6
  device_info_plus: ^11.2.0
  
  # مكتبات للبيانات والتخزين
  shared_preferences: ^2.5.3
  
  # مكتبات للPDF والمشاركة
  pdf: ^3.11.3
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
